client/package-lock.json
client/package.json
client/src/components/TopBar.js
client/src/styles/TopBar.css
package-lock.json

merge top bar to mongodb and api changes

Top bar, mongoDB and API

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/components/Home.js
client/src/components/Member.js
client/src/components/Members.js
client/src/components/MyProfile.js
client/src/components/TopBar.js
client/src/styles/TopBar.css
package-lock.json
package.json
server/app.js
server/models/member.js
server/package-lock.json
server/package.json
server/routes/api.js

Merged with Janne's top-bar branch and added it to all pages. Major changes; this should be merged before anyone else does anything.

API, MUI, react-router-dom, MongoDB, NavBar, Members list

---

.editorconfig

.editorconfig file for uniform handling of quotation and indentation across platforms. Many editors have built-in support for this, but e.g. VS Code needs an extension to be installed (takes 2 seconds). Check https://editorconfig.org/ (bottom of page) for info about whether your editor needs a plugin or not.

editorconfig setup

---

client/src/components/Home.js
client/src/styles/HomePage.css

When the user is an admin, the edit button is on the bottom left corner and the attending buttons will always be on the bottom right corner for all users.

Homepage: Ability for admins to attend events

---

client/package-lock.json
client/package.json
client/src/App.css
client/src/App.js
client/src/components/Home.js
client/src/components/Login.js
client/src/components/Members.js
client/src/components/Register.js
client/src/components/TopBar.js
client/src/styles/HomePage.css
client/src/styles/Login.css
client/src/styles/Register.css
package-lock.json
package.json
server/app.js
server/auth/passport.js
server/package-lock.json
server/package.json
server/routes/api.js
server/routes/controller.js

Added:
- Registration and login pages
- JWT auth token in sessionStorage
- Logout working (removes token from sessionStorage)
- Member list can only be viewed if authorized (token in sessionStorage/logged in)
- login button will dissapear when logged in and is replaced by logout button in the top bar
- Added 'register' button to appear in the top bar when not logged in
- My Profile disappears when logged out
- Password hash and salt (bcryptjs)
- isStrongPassword, isEmail when registering

Registration and login

---

client/src/components/TopBar.js
package-lock.json
package.json

Logout alert

---

client/src/components/TopBar.js
package-lock.json
package.json

Reverting that pr as it looks like it doesn't actually work properly

Revert "Logout alert"

---

client/package-lock.json
client/src/App.js
client/src/components/EventItem.js
client/src/components/Home.js
client/src/components/Login.js
client/src/modals/DeleteEventModal.js
client/src/styles/HomePage.css
server/models/event.js
server/routes/api.js

- Modal for deleting events
- Endpoint in the back-end for removing the event from the `Event` collection and removing all entries from the `Member_Event` collection related to said event
- Added a `ticketsSold` field into the Event model
- Success toast that is shown after successful event deletion
- Moved the event list update logic into a function
- Moved the EventItem to its own file to improve clarity in Home.js
- My linter changed the spacing slightly in HomePage.css, the actual change there is the justify mode for buttons in an EventItem, something like this:
- Also fixed a bug where the `currentUser`'s firstname and lastname weren't set after login, which meant that if you created an event after logging in, the "created by" would show "undefined undefined"
Screenshots:
Modal …

109 - Event deletion

---

client/src/components/TopBar.js
package-lock.json
package.json

Log out with notification and functionality

---

client/src/components/Members.js
client/src/components/Register.js
client/src/modals/CreateEventModal.js
client/src/styles/Members.css
client/src/styles/Modals.css
server/routes/api.js

The search gives results after each letter. Decided to make the search in the frontend after trying out other options. Fetching data from the backend everytime a letter was added was very slow. Alternatively, I can add a search button that fetches data from the backend after pressing it.

Member search and fixed labels for event creation

---

client/src/components/Member.js
client/src/components/Members.js
client/src/components/TopBar.js
client/src/modals/ConfirmDeleteMemberModal.js
client/src/modals/CreateEventModal.js
client/src/modals/DeleteEventModal.js
client/src/modals/EditDetailsModal.js
client/src/modals/EditEventModal.js
client/src/modals/ManageMemberModal.js
client/src/styles/Members.css
client/src/styles/Modals.css
server/models/member.js
server/routes/api.js

The admins can now update the roles and admin permissions for the members and also delete them from the Members page.
Also changed the CSS of the modals a little bit which causes issues on the way the confirm modals look when attenting to an event. But because they will be removed, I didn't waste time on fixing them.
Also these are on Trello as three separate tickets but I made them into a single PR to make it easier to test

408: roles for the members

---

client/src/components/Members.js
server/routes/api.js

- Currently logged in user is displayed first in the list of members
- Members are sorted in alphabetical order (firstname)

Changes in the way members are displayed

---

client/src/components/Home.js
client/src/components/MyProfile.js
client/src/modals/PayMembershipModal.js
server/models/member.js
server/routes/api.js

Membership payment works but it's pretty ugly implementation. Feel free to test.

Membership Payment

---

client/src/components/Member.js
client/src/components/Members.js
client/src/modals/GetMemberEmailsModal.js
client/src/styles/Members.css

The user can choose which seperator they use between emails

Get member emails

---

client/src/components/EventItem.js
client/src/components/Members.js
client/src/modals/GetMemberEmailsModal.js
client/src/modals/ListModal.js
client/src/styles/HomePage.css
client/src/styles/Modals.css
server/routes/api.js

Admins can see event participants and copy their emails.

409 - List of event participants

---

client/src/components/Member.js
client/src/components/MyProfile.js
client/src/modals/PayMembershipModal.js
client/src/styles/Members.css
client/src/styles/MyProfile.css
server/routes/api.js

The users can pay the membership from their profile page. If the membership is valid, it is displayed on their profile page and the expiration date of the membership is visible. If the expiration date is in two weeks or less, the button to renew the memberships will be visible.

404-02: Refined frontend for membership

---

client/src/components/EventItem.js

I dunno if this one is a better solution as it looks super scuffed also :D

renders event only after details have loaded

---

client/src/components/MyProfile.js
server/routes/users.js

Now teh token is updated when the user updates their information.

Email update crash fix

---

server/package-lock.json
server/package.json
server/routes/api.js

I created an email address for AssocEase (assocease@gmail.com) because I didn't want to use my personal email for this. Because gmail uses 2-factor authentication, an App Password was created for the email address that can be used to authenticate the email address. They are both hard coded at the moment and the App Password cannot be used to login normally to the gmail service.
The reminders work so that a function will run every hour and check if there are any events that will start in 23 - 24 hours. If there are events it will go through all the people that have bought a ticket to that event and sends them a reminder about the event. In my opinion it is enough that the function runs only every hour. I don't think it's necessary that the reminder comes exactly 24 hours before, but it can …

201: Event reminders

---

README.md
client/package-lock.json
client/package.json
client/public/index.html
client/src/App.js
client/src/components/AutocompleteInput.js
client/src/components/EventDetails.js
client/src/components/EventItem.js
client/src/components/Home.js
client/src/components/Map.js
client/src/components/MyProfile.js
client/src/modals/CreateEventModal.js
client/src/modals/EditEventModal.js
client/src/styles/Map.css
package-lock.json
package.json
server/models/event.js

There's quite a lot of stuff here, that's my bad - should have probably separated some into separate PRs. I'll try to run through the changes.
- Created components for the autocomplete location search and for the map
- Added logic to load the Google Places API in App.js
- Corrected the use of toasts in EventItem.js and Home.js (imported them from common/Toast and removed unnecessary ToastContainer from EventItem that was causing problems)
- Removed the leftover unused handleTimeChange function when editing events (we have separate functions for handling start and end time edits)
- Added some comments to the files I worked on
- Updated README and removed some leftovers from index.html
For these changes to work, check out the Google Maps api key from the news channel on Discord!

106-03: Event locations

---

server/routes/api.js

When events are edited, notifications are send to everyone who has a ticket for that event.
To test this:
- Make sure you have set your email correctly
- Buy a ticket to an event
- Edit that event
- You should have a notification in your inbox
I will not merge this PR before Janne's event location PR is merged. This still uses the locations as strings and it will be fixed once I get the changes from that PR. But you can test everything else in this already.

203: Event edition notification

---

client/src/components/Login.js
client/src/components/TopBar.js

- Removed "forgot password" paragraph
- Made the AssocEase text in the top-left a link to the home page

Small fixes

---

client/src/components/EventItem.js
client/src/modals/CreateEventModal.js
client/src/modals/EditEventModal.js
client/src/styles/HomePage.css
client/src/styles/Scheduler.css
server/routes/api.js

- Fixed issue where 'Member_Event' was imported twice with different case
- Fixed issue where events were reloaded when the user removed a like to an event they don't have a ticket to
- Changed ticket checking from POST to GET
- Removed unnecessary code in server/routes/api.js
- optimized ticket checking function
- Fixed bug where '\n' wasn't displayed in event items
- Added minRows and maxRows to description input boxes when creating and editing events
- Centered eventItem in Scheduler

Optimization and UI fixes
